import os
from sqlite3 import connect

class BaseDatos():
    def __init__(self) -> None:
        self.Crear_Tablas()
    ################################# CONECTAR BASE DE DATOS
    def conectar(self):
        con = connect('modulos/BasesDatos/DataBase.db')
        return con,con.cursor()

    ################################# CREAR TABLAS
    def Crear_Tablas(self):
        if os.path.exists('modulos/BasesDatos/DataBase.db') ==False:
            con,cursor=self.conectar()     
            cursor.execute("CREATE TABLE IF NOT EXISTS TRANSMISION(ID_TRANSMISION INTEGER PRIMARY KEY, TIPO TEXT, DESCRIPCION TEXT)")
            cursor.execute("CREATE TABLE IF NOT EXISTS DEPARTAMENTOS(ID_DEPARTAMENTO INTEGER PRIMARY KEY AUTOINCREMENT, NOMBRE TEXT, DESCRIPCION TEXT)")
            cursor.execute("CREATE TABLE IF NOT EXISTS UNIDADES_INTERNET(ID_UNIDAD TEXT PRIMARY KEY, NOMBRE_UNIDAD TEXT,CORD TEXT, SERVICIO_UNIDAD TEXT, PROVEEDOR_UNIDAD TEXT, OBSERVACIONES TEXT, FECHA_UNIDAD TEXT, TEL_UNIDAD TEXT, ID_TRANSMISION INTEGER, FOREIGN KEY (ID_TRANSMISION) REFERENCES TRANSMISION(ID_TRANSMISION) ON UPDATE CASCADE ON DELETE CASCADE)")
            cursor.execute("CREATE TABLE IF NOT EXISTS PROVEEDOR(ID_PROVEEDOR INTEGER PRIMARY KEY AUTOINCREMENT, NOMBRE TEXT, DESCRIPCION TEXT, FECHA TEXT, TELEFONO TEXT,ID_TRANSMISION INTEGER, FOREIGN KEY (ID_TRANSMISION) REFERENCES TRANSMISION(ID_TRANSMISION) ON UPDATE CASCADE ON DELETE CASCADE)")
            cursor.execute("CREATE TABLE IF NOT EXISTS REPORTES(ID_REPORTE INTEGER PRIMARY KEY AUTOINCREMENT, FOLIO TEXT, DESCRIPCION TEXT, FECHA TEXT, ACUDIO TEXT, REMOTO_SITIO TEXT,MOTIVO TEXT, TELEFONO TEXT, ATENDIO TEXT, ID_PROVEEDOR INTEGER, FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR(ID_PROVEEDOR) ON UPDATE CASCADE ON DELETE CASCADE)")
            cursor.execute("CREATE TABLE IF NOT EXISTS RED(ID_RED INTEGER PRIMARY KEY AUTOINCREMENT, SSID TEXT, PASSWORD TEXT, SUBIDA REAL, BAJADA REAL, ID_PROVEEDOR INTEGER, FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR(ID_PROVEEDOR) ON UPDATE CASCADE ON DELETE CASCADE)")
            cursor.execute("CREATE TABLE IF NOT EXISTS HISTORIAL_NUM_CONEXIONES(ID_HISTORIAL_NUM_CONEXIONES INTEGER PRIMARY KEY AUTOINCREMENT, ID_RED INTEGER,FECHA TEXT,NUMERO INT, FOREIGN KEY (ID_RED) REFERENCES RED (ID_RED) ON UPDATE CASCADE)")
            cursor.execute("CREATE TABLE IF NOT EXISTS HISTORIAL_CONEXIONES(ID_HISTORIAL_CONEXIONES INTEGER PRIMARY KEY AUTOINCREMENT,FECHA TEXT,ID_RED INTEGER, NOMBRE_HOST TEXT, IP_HOST TEXT, MAC_HOST TEXT, VENDOR TEXT, FOREIGN KEY (ID_RED) REFERENCES RED(ID_RED))")
            cursor.execute("CREATE TABLE IF NOT EXISTS CONTROL_RED_ESPECIFICA(ID_CONTROL_RED_ESPECIFICA INTEGER PRIMARY KEY AUTOINCREMENT, ID_RED INTEGER, IP_HOST TEXT, NO_INV TEXT, STATUS TEXT, MAC_HOST TEXT, USUARIO TEXT, FECHA TEXT, OBSERVACIONES TEXT, USUARIO_DIS TEXT,VERIFICADO TEXT,TIPO TEXT, ID_DEPARTAMENTO INT, VENDOR TEXT,  FOREIGN KEY (ID_RED) REFERENCES RED(ID_RED) ON UPDATE CASCADE, FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTOS (ID_DEPARTAMENTO) ON UPDATE CASCADE)")
            cursor.execute("CREATE TABLE IF NOT EXISTS PRUEBAS_VELOCIDAD(ID_PRUEBAS_VELOCIDAD INTEGER PRIMARY KEY AUTOINCREMENT, ID_RED INTEGER, FECHA TEXT, HORA TEXT,HOST TEXT, SPONSOR TEXT,SUBIDA FLOAT, BAJADA FLOAT,PINGS FLOAT, PINGB FLOAT, PING FLOAT, RESULTADO TEXT, FOREIGN KEY (ID_RED) REFERENCES RED(ID_RED) ON UPDATE CASCADE)")
            cursor.execute("CREATE TABLE IF NOT EXISTS DISPOSITIVOS(ID_DISPOSITIVO INTEGER PRIMARY KEY AUTOINCREMENT,NOINV TEXT, NOMBRE TEXT, DESCRIPCION TEXT, UBICACION TEXT, TIPO_CONEXION TEXT, ID_RED INTEGER, ID_DEPARTAMENTO INTEGER, FOREIGN KEY (ID_RED) REFERENCES RED(ID_RED) ON UPDATE CASCADE,  FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTOS (ID_DEPARTAMENTO) ON UPDATE CASCADE)")
            cursor.execute("CREATE TABLE IF NOT EXISTS PROBLEMAS_RED(ID_PROBLEMA INTEGER PRIMARY KEY AUTOINCREMENT, DESCRIPCION TEXT, FECHA TEXT, SOLUCION TEXT, CORREGIDO TEXT, FECHA_CORRECCION TEXT, ID_RED INTEGER,ID_DEPARTAMENTO INTEGER, FOREIGN KEY (ID_RED) REFERENCES RED(ID_RED) ON UPDATE CASCADE,  FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTOS (ID_DEPARTAMENTO) ON UPDATE CASCADE)")  
            cursor.execute("INSERT INTO TRANSMISION VALUES(1,'Inalámbrico ','Transmisión por antenas punto a punto.')")
            cursor.execute("INSERT INTO TRANSMISION VALUES(2,'Satelital','Transmisión de red por medio de satelites.')")
            cursor.execute("INSERT INTO TRANSMISION VALUES(3,'Telefónico (Dial-Up)','Consta en el acceso a Internet a través de un MODEM (1) telefónico y desde una línea del servicio básico de telefonía.')")
            cursor.execute("INSERT INTO TRANSMISION VALUES(4,'Fibra Optica','Transmisión por cables de fibra optica de alta velocidad.')")
            cursor.execute("INSERT INTO TRANSMISION VALUES(5,'ADSL','Se caracteriza por utilizar para el tráfico de datos el mismo cable telefónico que para las transmisiones de voz.')")
            cursor.execute("INSERT INTO TRANSMISION VALUES(6,'Cablemodem','Provista por las prestadoras de televisión por cable quienes poseen en su estructura de red un troncal de fibra óptica.')")
            cursor.execute("INSERT INTO TRANSMISION VALUES(7,'Red de Telefonía Móvil','Acceso a la red desde la compañia de telefonia movil')")
            cursor.execute("INSERT INTO TRANSMISION VALUES(8,'Línea Eléctrica','Instalaciones de red desde la luz electrica.')")
            cursor.execute("INSERT INTO DEPARTAMENTOS VALUES(1,'POR DEFECTO','POR DEFECTO')")
            cursor.execute("INSERT INTO PROVEEDOR VALUES(1,'POR DEFECTO','POR DEFECTO','POR DEFECTO','POR DEFECTO',1)")
            cursor.execute("INSERT INTO REPORTES VALUES(1, 'POR DEFECTO', 'POR DEFECTO','POR DEFECTO', 'POR DEFECTO', 'POR DEFECTO','POR DEFECTO', 'POR DEFECTO', 'POR DEFECTO', 1)")
            cursor.execute("INSERT INTO RED VALUES(1, 'POR DEFECTO', 'POR DEFECTO', 0,0, 1)")
            cursor.execute("INSERT INTO HISTORIAL_NUM_CONEXIONES VALUES(1, 1,'POR DEFECTO',0)")
            cursor.execute("INSERT INTO HISTORIAL_CONEXIONES VALUES(1,'POR DEFECTO',1,'POR DEFECTO', 'POR DEFECTO', 'POR DEFECTO', 'POR DEFECTO')")
            cursor.execute("INSERT INTO CONTROL_RED_ESPECIFICA VALUES(1, 1, 'POR DEFECTO', 'POR DEFECTO', 'POR DEFECTO', 'POR DEFECTO', 'POR DEFECTO', 'POR DEFECTO', 'POR DEFECTO', 'POR DEFECTO','POR DEFECTO','POR DEFECTO', 1, 'POR DEFECTO')")
            cursor.execute("INSERT INTO PRUEBAS_VELOCIDAD VALUES(1, 1, 'POR DEFECTO','POR DEFECTO','POR DEFECTO','POR DEFECTO', 0,0,0,0,0, 'POR DEFECTO')")
            cursor.execute("INSERT INTO DISPOSITIVOS VALUES(1,'POR DEFECTO', 'POR DEFECTO', 'POR DEFECTO', 'POR DEFECTO', 'POR DEFECTO', 1, 1)")
            cursor.execute("INSERT INTO PROBLEMAS_RED VALUES(1, 'POR DEFECTO', 'POR DEFECTO', 'POR DEFECTO', 'POR DEFECTO', 'POR DEFECTO', 1,1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA002884','21','CONCEPCIÓN LOS BAÑOS','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA002901','21','GUADALUPE CACHI','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA002913','21','JALPA DE LOS BAÑOS','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA002942','21','SAN CRISTÓBAL DE LOS BAÑOS','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA002995','21','SAN PABLO DE LOS REMEDIOS','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA003012','21','SAN PEDRO DE LOS BAÑOS II','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA003024','21','SAN PEDRO DE LOS BAÑOS I','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA003041','21','SANTA ANA LA LADERA','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA003065','21','EMILIANO ZAPATA','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA003070','21','SANTO DOMINGO DE GUZMÁN','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA003082','21','GUADALUPE DEL RÍO','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA003094','21','SAN FRANCISCO DEL RÍO','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA010135','21','C.S. SAN IGNACIO DEL PEDREGAL','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA017094','21','LA CONCEPCIÓN DE LOS BAÑOS III','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA017106','21','SAN PEDRO DE LOS BAÑOS III','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA017111','21','SAN FRANCISCO DE GUZMAN','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA017123','21','EMILIANO ZAPATA III','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA017135','21','JALPA DE DOLORES','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA017403','21','SAN MATEO IXTLÁHUACA','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA002896','22','LA GUADALUPANA','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA002925','22','SAN ANDRÉS DEL PEDREGAL','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA002930','22','SAN BARTOLO DEL LLANO','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA002954','22','SAN ILDELFONSO PROFESORA ELDA GÓMEZ LUGO','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA002966','22','SAN JERONIMO IXTAPANTONGO','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA002971','22','SAN JOAQUÍN LA CABECERA','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA002983','22','SAN LORENZO TOXICO','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA003000','22','SAN PEDRO BARRIO','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA003036','22','SANTA ANA IXTLAHUACA','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA003053','22','SANTA MARÍA DEL LLANO','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA010140','22','C.S. SAN FRANCISCO IXTLAHUACA','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA010724','22','CENTRO DE SALUD SAN MIGUEL ENYEGE','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA010736','22','CENTRO DE SALUD LA CONCEPCIÓN ENYEGE','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA014110','22','SAN JOAQUÍN EL JUNCO PROFESORA INÉS ÁNGELES SALAZAR','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA014152','22','SAN ANTONIO BONIXI','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA014512','22','CENTRO DE SALUD RINCÓN DE LOS PERALES','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA017140','22','SAN ISIDRO BOXIPÉ','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA003374','23','JIQUIPILCO','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA003386','23','BUENOS AIRES','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA003391','23','LOMA HIDALGO','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA003403','23','EJIDO LOMA DE MALACOTA','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA003415','23','MOXTEJE','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA003420','23','PORTEZUELOS','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA003432','23','SAN BARTOLO OXTOTITLÁN','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA003444','23','SAN FELIPE SANTIAGO','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA003456','23','SAN JOSÉ DEL SITIO','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA003461','23','SAN MIGUEL YUXTEPEC','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA003473','23','SANTA CRUZ TEPEXPAN','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA003485','23','SANTA MARÍA NATIVITAS','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA003490','23','EJIDO LLANO GRANDE','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA003502','23','MANZANA QUINTA','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA003514','23','MANZANA SEXTA','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA010951','23','U. MÓVIL ISEM RANCHO ALEGRE','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA016061','23','SAN ANTONIO NIXINÍ','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA003526','24','JOCOTITLÁN','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA003531','24','MAVORO','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA003543','24','PROVIDENCIA','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA003560','24','SAN FRANCISCO CHEJE','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA003572','24','SAN JUAN COAJOMULCO','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA003584','24','SAN MIGUEL TENOCHTITLAN','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA003601','24','SANTA MARÍA ENDARE','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA003613','24','SANTIAGO CASANDEJE','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA003625','24','SANTIAGO YECHE','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA003630','24','TIACAQUE','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA003642','24','HUEMETLA','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA010461','24','CENTRO DE SALUD SANTA MARÍA  CITENDEJE','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA010485','24','CENTRO DE SALUD LOS REYES','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA017514','24','BARRIO LA LUZ','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA018902','24','CEAPS JOCOTITLAN DR. ADRIÁN CORREA CEDILLO','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA003951','25','CEAPS SAN BARTOLO MORELOS','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA003963','25','SAN GREGORIO MACAPEXCO','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA003975','25','SAN JOSÉ LA EPIFANIA','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA003980','25','SAN LORENZO MALACOTA','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA003992','25','SAN MARCOS TLAZALPAN','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA004004','25','SAN SEBASTIAN BUENOS AIRES','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA004016','25','SANTA CLARA DE JUÁREZ','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA004021','25','TLALPUJAHUILLA','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA004033','25','BARRIO CUARTO LA LOMA','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA004045','25','COLONIA FRANCISCO I.MADERO','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA017152','25','EJIDO SAN ANTONIO','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA005112','26','CARMEN OCOTEPEC','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA005124','26','CHICHILPA','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA005136','26','DOLORES HIDALGO','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA005141','26','EMILIO PORTES GIL','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA005170','26','PURÍSIMA CONCEPCIÓN MAYORAZGO','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA005182','26','RINCÓN DE LOS PIRULES','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA005194','26','RIOYOS BUENAVISTA','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA005206','26','SAN AGUSTÍN MEXTEPEC','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA005223','26','SAN ANTONIO MEXTEPEC','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA005293','26','SAN PABLO TLALCHICHILPA','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA005322','26','EL TUNAL NENAXI','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA010152','26','C.S. CHOTEJE','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA010164','26','C.S. SAN JUAN JALPA','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA010333','26','C.S. EL TUNAL, SAN FELIPE DEL PROGRESO','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA014563','26','CENTRO DE SALUD CONCEPCIÓN CABECERA','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA016440','26','U. MÓVIL ISEM TUNGAREO','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA016720','26','PALMILLAS','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA017164','26','DOTEGIARE','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA017181','26','EJIDO SAN JUAN JALPA','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA005100','27','CALVARIO DEL CARMEN','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA005153','27','FRESNO NICHI','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA005165','27','SAN ANTONIO DE LAS HUERTAS','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA005211','27','SAN ANTONIO LA CIÉNEGA','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA005235','27','SAN JERONIMO BONCHETE','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA005252','27','SAN JUAN COTE EJIDO','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA005276','27','SAN MIGUEL LA LABOR','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA005281','27','SAN NICOLÁS GUADALUPE','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA005305','27','SAN PEDRO EL ALTO','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA005310','27','SANTA ANA NICHI EJIDO','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA005334','27','LA VIRGEN','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA010176','27','C.S. SAN JERÓNIMO MAVATI','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA010765','27','CENTRO DE SALUD SANTA ANA NICHI CENTRO','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA010782','27','CENTRO DE SALUD DIOS PADRE','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA010794','27','CENTRO DE SALUD LA SOLEDAD','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA016732','27','LAS PALOMAS','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA017176','27','BOREJE','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA018033','27','U. MÓVIL ISEM ZARAGOZA','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA008991','28','CONCEPCIÓN DE LA VENTA','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA009003','28','CONCEPCIÓN DEL MONTE','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA009020','28','GUARDA DE  GUADALUPE','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA009032','28','GUARDA DE LA LAGUNITA','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA009044','28','GUARDA LA LAGUNITA EL PUEBLITO','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA009085','28','PALO AMARILLO','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA009126','28','ROSA DE PALO AMARILLO','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA009155','28','SAN FELIPE DE JESÚS','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA009160','28','COORDINACION MUNICIPAL SAN JOSÉ DEL RINCÓN NORTE','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA009184','28','SAN MIGUEL DEL CENTRO','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA009196','28','SAN ONOFRE CENTRO','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA009213','28','EJIDO DE LA SOLEDAD','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA010181','28','C.S. PATHE DE MULA LOS CEDROS','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA010741','28','CENTRO DE SALUD CEDRO DE LA MANZANA','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA016650','28','U. MÓVIL ISEM  GARATACHEA','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA016691','28','SANTA CRUZ DEL TEJOCOTE','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA016703','28','SAN FRANCISCO SOLO','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA018511','28','CEAPS SAN JOSÉ DEL RINCÓN','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA009015','29','GUADALUPE BUENAVISTA','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA009056','29','PURISIMA JALTEPEC','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA009073','29','LA MESA','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA009090','29','SAN JUAN PALO SECO','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA009114','29','PROVIDENCIA','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA009131','29','LAS ROSAS','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA009143','29','SAN ANTONIO PUEBLO NUEVO','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA009172','29','SAN MIGUEL AGUA BENDITA','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA009230','29','SAN JOAQUÍN LA MILLAS','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA009242','29','RAMEJE','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA015233','29','C.S. LOS LOBOS','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA015245','29','C.S. AGUA ZARCA PUEBLO NUEVO','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA016686','29','EL PINTAL','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA016715','29','SAN DIEGO PUEBLO NUEVO','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA017794','29','CARAVANA DE SALUD GUADALUPE CHICO','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA017946','29','U. MÓVIL ISEM FUNDEREJE','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA018634','29','MINITA DEL CEDRO','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA018646','29','LA TRAMPA','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA018651','29','YONDECE','Con Servicio','','','','',1)")
            cursor.execute("INSERT INTO UNIDADES_INTERNET VALUES('MCSSA015316','JURISDICCION','JURISDICCIÓN SANITARIA II. IXTLÁHUACA','Con Servicio','','','','',1)")
            con.commit()
            cursor.close()
            con.close()

    def ejecutarAccion(self,TRANSACCION):
        con,cursor=self.conectar()
        a=True
        cursor.execute(TRANSACCION)
        con.commit()
        print("Realizado con exito")
        cursor.close()
        con.close()
        return a    

    ################################# INSERTAR REGISTROS
    def insertarTRANSMISION(self,TIPO,DESCRIPCION):
        return self.ejecutarAccion(f"INSERT INTO TRANSMISION(TIPO,DESCRIPCION) VALUES('{TIPO}','{DESCRIPCION}')")
    def insertarUNIDADES_INTERNET(self,ID_UNIDAD, NOMBRE_UNIDAD, CORD,SERVICIO_UNIDAD, PROVEEDOR_UNIDAD, OBSERVACIONES, FECHA_UNIDAD, TEL_UNIDAD, ID_TRANSMISION):
        return self.ejecutarAccion(f"INSERT INTO UNIDADES_INTERNET(ID_UNIDAD, NOMBRE_UNIDAD,CORD, SERVICIO_UNIDAD, PROVEEDOR_UNIDAD, OBSERVACIONES, FECHA_UNIDAD, TEL_UNIDAD, ID_TRANSMISION) VALUES('{ID_UNIDAD}', '{NOMBRE_UNIDAD}','{CORD}', '{SERVICIO_UNIDAD}', '{PROVEEDOR_UNIDAD}', '{OBSERVACIONES}', '{FECHA_UNIDAD}', '{TEL_UNIDAD}', {ID_TRANSMISION})")
    def insertarPROVEEDOR(self, NOMBRE, DESCRIPCION, FECHA, TELEFONO,ID_TRANSMISION):
        return self.ejecutarAccion(f"INSERT INTO PROVEEDOR(NOMBRE, DESCRIPCION, FECHA, TELEFONO,ID_TRANSMISION) VALUES('{NOMBRE}', '{DESCRIPCION}', '{FECHA}','{TELEFONO}',{ID_TRANSMISION})")
    def insertarREPORTES(self,FOLIO, DESCRIPCION, FECHA, ACUDIO, REMOTO_SITIO,MOTIVO, TELEFONO, ATENDIO, ID_PROVEEDOR):
        return self.ejecutarAccion(f"INSERT INTO REPORTES(FOLIO, DESCRIPCION, FECHA, ACUDIO, REMOTO_SITIO,MOTIVO, TELEFONO, ATENDIO, ID_PROVEEDOR) VALUES('{FOLIO}', '{DESCRIPCION}', '{FECHA}', '{ACUDIO}', '{REMOTO_SITIO}','{MOTIVO}', '{TELEFONO}', '{ATENDIO}', {ID_PROVEEDOR})")
    def insertarRED(self,SSID, PASSWORD, SUBIDA, BAJADA, ID_PROVEEDOR):
        return self.ejecutarAccion(f"INSERT INTO RED(SSID, PASSWORD, SUBIDA, BAJADA, ID_PROVEEDOR) VALUES('{SSID}', '{PASSWORD}', {SUBIDA}, {BAJADA}, {ID_PROVEEDOR})")
    def insertarHISTORIAL_NUM_CONEXIONES(self,ID_RED,FECHA,NUMERO):
        return self.ejecutarAccion(f"INSERT INTO HISTORIAL_NUM_CONEXIONES(ID_RED,FECHA,NUMERO) VALUES({ID_RED},'{FECHA}',{NUMERO})")
    def insertarHISTORIAL_CONEXIONES(self,ID_RED,FECHA, NOMBRE_HOST, IP_HOS, MAC_HOST, VENDOR):
        return self.ejecutarAccion(f"INSERT INTO HISTORIAL_CONEXIONES(FECHA,ID_RED, NOMBRE_HOST, IP_HOST, MAC_HOST, VENDOR) VALUES('{FECHA}',{ID_RED}, '{NOMBRE_HOST}', '{IP_HOS}', '{MAC_HOST}', '{VENDOR}')")
    def insertarCONTROL_RED_ESPECIFICA(self,ID_RED, IP_HOST, NO_INV, STATUS, MAC_HOST, USUARIO, FECHA, OBSERVACIONES, USUARIO_DIS,VERIFICADO,TIPO,ID_DEP,VENDOR):
        return self.ejecutarAccion(f"INSERT INTO CONTROL_RED_ESPECIFICA(ID_RED, IP_HOST, NO_INV, STATUS, MAC_HOST, USUARIO, FECHA, OBSERVACIONES, USUARIO_DIS,VERIFICADO,TIPO,ID_DEPARTAMENTO,VENDOR) VALUES({ID_RED},'{IP_HOST}', '{NO_INV}', '{STATUS}', '{MAC_HOST}', '{USUARIO}', '{FECHA}', '{OBSERVACIONES}', '{USUARIO_DIS}','{VERIFICADO}','{TIPO}',{ID_DEP},'{VENDOR}')")
    def insertarPRUEBAS_VELOCIDAD(self,ID_RED,FECHA,HORA,HOST,SPONSOR,SUBIDA, BAJADA,PINGS,PINGB,PING, RESULTADO):
        return self.ejecutarAccion(f"INSERT INTO PRUEBAS_VELOCIDAD(ID_RED,FECHA,HORA,HOST,SPONSOR,SUBIDA, BAJADA,PINGS,PINGB,PING, RESULTADO) VALUES({ID_RED},'{FECHA}','{HORA}','{HOST}','{SPONSOR}',{SUBIDA}, {BAJADA},{PINGS},{PINGB},{PING}, '{RESULTADO}')")
    def insertarDISPOSITIVOS(self,NOINV,NOMBRE, DESCRIPCION, UBICACION, TIPO_CONEXION, ID_RED,ID_DEPARTAMENTO):
        return self.ejecutarAccion(f"INSERT INTO DISPOSITIVOS(NOINV,NOMBRE, DESCRIPCION, UBICACION, TIPO_CONEXION, ID_RED,ID_DEPARTAMENTO) VALUES('{NOINV}','{NOMBRE}', '{DESCRIPCION}', '{UBICACION}', '{TIPO_CONEXION}', {ID_RED},{ID_DEPARTAMENTO})")
    def insertarPROBLEMAS_RED(self,DESCRIPCION, FECHA, SOLUCION, CORREGIDO, FECHA_CORRECCION, ID_RED,ID_DEPARTAMENTO):
        return self.ejecutarAccion(f"INSERT INTO PROBLEMAS_RED(DESCRIPCION, FECHA, SOLUCION, CORREGIDO, FECHA_CORRECCION, ID_RED,ID_DEPARTAMENTO) VALUES('{DESCRIPCION}', '{FECHA}', '{SOLUCION}', '{CORREGIDO}', '{FECHA_CORRECCION}', {ID_RED},{ID_DEPARTAMENTO})")
    def insertarDEPARTAMENTOS(self,NOMBRE,DESCRIPCION):
        return self.ejecutarAccion(f"INSERT INTO DEPARTAMENTOS(NOMBRE,DESCRIPCION) VALUES('{NOMBRE}','{DESCRIPCION}')")
    ####################### BORRAR REGISTROS
    def borrarTRANSMISION(self,ID):
        return self.ejecutarAccion(f"DELETE FROM TRANSMISION WHERE ID_TRANSMISION={ID}")
    def borrarUNIDADES_INTERNET(self,ID):
        return self.ejecutarAccion(f"DELETE FROM UNIDADES_INTERNET WHERE ID_UNIDAD='{ID}'")
    def borrarPROVEEDOR(self,ID):
        return self.ejecutarAccion(f"DELETE FROM PROVEEDOR WHERE ID_PROVEEDOR={ID}")
    def borrarTELEFONO_PROVEEDOR(self,ID):
        return self.ejecutarAccion(f"DELETE FROM TELEFONO_PROVEEDOR WHERE ID_TELEFONO={ID}")
    def borrarREPORTES(self,ID):
        return self.ejecutarAccion(f"DELETE FROM REPORTES WHERE ID_REPORTE={ID}")
    def borrarRED(self,ID):
        return self.ejecutarAccion(f"DELETE FROM RED WHERE ID_RED={ID}")
    def borrarHISTORIAL_NUM_CONEXIONES(self,ID):
        return self.ejecutarAccion(f"DELETE FROM HISTORIAL_NUM_CONEXIONES WHERE ID_HISTORIAL_NUM_CONEXIONES={ID}")
    def borrarHISTORIAL_CONEXIONES(self,ID):
        return self.ejecutarAccion(f"DELETE FROM HISTORIAL_CONEXIONES WHERE ID_HISTORIAL_CONEXIONES={ID}")
    def borrarCONTROL_RED_ESPECIFICA(self,ID):
        return self.ejecutarAccion(f"DELETE FROM CONTROL_RED_ESPECIFICA WHERE ID_CONTROL_RED_ESPECIFICA={ID}")
    def borrarPRUEBAS_VELOCIDAD(self,ID):
        return self.ejecutarAccion(f"DELETE FROM PRUEBAS_VELOCIDAD WHERE ID_PRUEBAS_VELOCIDAD={ID}")
    def borrarDISPOSITIVOS(self,ID):
        return self.ejecutarAccion(f"DELETE FROM DISPOSITIVOS WHERE ID_DISPOSITIVO={ID}")
    def borrarPROBLEMAS_RED(self,ID):
        return self.ejecutarAccion(f"DELETE FROM PROBLEMAS_RED WHERE ID_PROBLEMA={ID}")
    def borrarDEPARTAMENTOS(self,ID):
        return self.ejecutarAccion(f"DELETE FROM DEPARTAMENTOS WHERE ID_DEPARTAMENTO={ID}")

    ################# MODIFICAR REGISTROS
    def modificarTRANSMISION(self,ID_TRANSMISION,TIPO,DESCRIPCION):
        return self.ejecutarAccion(f"UPDATE TRANSMISION SET TIPO='{TIPO}',DESCRIPCION='{DESCRIPCION}' WHERE ID_TRANSMISION={ID_TRANSMISION}")
    def modificarUNIDADES_INTERNET(self,ID_UNIDAD, NOMBRE_UNIDAD,CORD ,SERVICIO_UNIDAD, PROVEEDOR_UNIDAD, OBSERVACIONES, FECHA_UNIDAD, TEL_UNIDAD, ID_TRANSMISION):
        return self.ejecutarAccion(f"UPDATE UNIDADES_INTERNET  SET NOMBRE_UNIDAD='{NOMBRE_UNIDAD}',CORD='{CORD}', SERVICIO_UNIDAD='{SERVICIO_UNIDAD}', PROVEEDOR_UNIDAD='{PROVEEDOR_UNIDAD}', OBSERVACIONES='{OBSERVACIONES}', FECHA_UNIDAD='{FECHA_UNIDAD}', TEL_UNIDAD='{TEL_UNIDAD}', ID_TRANSMISION={ID_TRANSMISION} WHERE ID_UNIDAD='{ID_UNIDAD}' ")
    def modificarPROVEEDOR(self,ID_PROVEEDOR, NOMBRE, DESCRIPCION, FECHA,TELEFONO, ID_TRANSMISION):
        return self.ejecutarAccion(f"UPDATE PROVEEDOR SET NOMBRE='{NOMBRE}', DESCRIPCION='{DESCRIPCION}', FECHA='{FECHA}',TELEFONO='{TELEFONO}', ID_TRANSMISION={ID_TRANSMISION}  WHERE ID_PROVEEDOR={ID_PROVEEDOR} ")
    def modificarREPORTES(self,ID_REPORTE, FOLIO, DESCRIPCION, FECHA, ACUDIO, REMOTO_SITIO,MOTIVO, TELEFONO, ATENDIO, ID_PROVEEDOR):
        return self.ejecutarAccion(f"UPDATE REPORTES SET FOLIO='{FOLIO}', DESCRIPCION='{DESCRIPCION}', FECHA='{FECHA}', ACUDIO='{ACUDIO}', REMOTO_SITIO='{REMOTO_SITIO}',MOTIVO='{MOTIVO}', TELEFONO='{TELEFONO}',ATENDIO='{ATENDIO}', ID_PROVEEDOR={ID_PROVEEDOR} WHERE ID_REPORTE={ID_REPORTE}")
    def modificarRED(self,ID_RED, SSID, PASSWORD, SUBIDA, BAJADA, ID_PROVEEDOR):
        return self.ejecutarAccion(f"UPDATE RED SET SSID='{SSID}', PASSWORD='{PASSWORD}', SUBIDA={SUBIDA}, BAJADA={BAJADA}, ID_PROVEEDOR={ID_PROVEEDOR} WHERE ID_RED={ID_RED}")
    def modificarHISTORIAL_NUM_CONEXIONES(self,ID_HISTORIAL_NUM_CONEXIONES,ID_RED,FECHA,NUMERO):
        return self.ejecutarAccion(f"UPDATE HISTORIAL_NUM_CONEXIONES SET ID_RED={ID_RED}, FECHA='{FECHA}',NUMERO={NUMERO} WHERE ID_HISTORIAL_NUM_CONEXIONES={ID_HISTORIAL_NUM_CONEXIONES}")
    def modificarHISTORIAL_CONEXIONES(self,ID_HISTORIAL_CONEXIONES,FECHA,ID_RED, NOMBRE_HOST, IP_HOS, MAC_HOST, VENDOR):
        return self.ejecutarAccion(f"UPDATE HISTORIAL_CONEXIONES SET FECHA='{FECHA}',ID_RED={ID_RED}, NOMBRE_HOST='{NOMBRE_HOST}', IP_HOST='{IP_HOS}', MAC_HOST='{MAC_HOST}', VENDOR='{VENDOR}'  WHERE ID_HISTORIAL_CONEXIONES={ID_HISTORIAL_CONEXIONES} ")
    def modificarCONTROL_RED_ESPECIFICA(self,ID_CONTROL_RED_ESPECIFICA,ID_RED, IP_HOST, NO_INV, STATUS, MAC_HOST, USUARIO, FECHA, OBSERVACIONES, USUARIO_DIS,VERIFICADO,TIPO,ID_DEPARTAMENTO,VENDOR):
        return self.ejecutarAccion(f"UPDATE CONTROL_RED_ESPECIFICA SET ID_RED={ID_RED}, IP_HOST='{IP_HOST}', NO_INV='{NO_INV}', STATUS='{STATUS}', MAC_HOST='{MAC_HOST}', USUARIO='{USUARIO}', FECHA='{FECHA}', OBSERVACIONES='{OBSERVACIONES}', USUARIO_DIS='{USUARIO_DIS}', VERIFICADO='{VERIFICADO}',TIPO='{TIPO}',ID_DEPARTAMENTO={ID_DEPARTAMENTO},VENDOR='{VENDOR}' WHERE ID_CONTROL_RED_ESPECIFICA={ID_CONTROL_RED_ESPECIFICA}")
    def modificarPRUEBAS_VELOCIDAD(self,ID_PRUEBAS_VELOCIDAD,ID_RED,FECHA,HORA,HOST,SPONSOR,SUBIDA, BAJADA,PINGS,PINGB,PING, RESULTADO):
        return self.ejecutarAccion(f"UPDATE PRUEBAS_VELOCIDAD SET ID_RED={ID_RED},FECHA='{FECHA}',HORA='{HORA}',HOST='{HOST}',SPONSOR='{SPONSOR}',SUBIDA={SUBIDA}, BAJADA={BAJADA},PINGS={PINGS},PINGB={PINGB},PING={PING}, RESULTADO='{RESULTADO}' WHERE ID_PRUEBAS_VELOCIDAD={ID_PRUEBAS_VELOCIDAD}")
    def modificarDISPOSITIVOS(self,ID_DISPOSITIVO,NOINV, NOMBRE, DESCRIPCION, UBICACION, TIPO_CONEXION, ID_RED,ID_DEPARTAMENTO):
        return self.ejecutarAccion(f"UPDATE DISPOSITIVOS SET NOINV='{NOINV}', NOMBRE='{NOMBRE}', DESCRIPCION='{DESCRIPCION}', UBICACION='{UBICACION}', TIPO_CONEXION='{TIPO_CONEXION}', ID_RED={ID_RED},  ID_DEPARTAMENTO={ID_DEPARTAMENTO} WHERE ID_DISPOSITIVO={ID_DISPOSITIVO}")
    def modificarPROBLEMAS_RED(self,ID_PROBLEMA, DESCRIPCION, FECHA, SOLUCION, CORREGIDO, FECHA_CORRECCION, ID_RED,ID_DEPARTAMENTO):
        return self.ejecutarAccion(f"UPDATE PROBLEMAS_RED SET DESCRIPCION='{DESCRIPCION}', FECHA='{FECHA}', SOLUCION='{SOLUCION}',CORREGIDO='{CORREGIDO}',FECHA_CORRECCION='{FECHA_CORRECCION}', ID_RED={ID_RED}, ID_DEPARTAMENTO={ID_DEPARTAMENTO} WHERE ID_PROBLEMA={ID_PROBLEMA} ")
    def modificarDEPARTAMENTOS(self,ID_DEPARTAMENTO,NOMBRE,DESCRIPCION):
        return self.ejecutarAccion(f"UPDATE DEPARTAMENTOS SET NOMBRE='{NOMBRE}', DESCRIPCION='{DESCRIPCION}' WHERE ID_DEPARTAMENTO={ID_DEPARTAMENTO}")
    ############## CONSULTAS
    def consultar(self,CONSULTA):
        con,cursor=self.conectar()
        cursor.execute(CONSULTA)
        datos = cursor.fetchall()
        cursor.close()
        con.close()
        return datos
    def consultarTRANSMISION(self):
        return self.consultar("SELECT * FROM TRANSMISION")
    def consultarDEPARTAMENTOS(self):
        return self.consultar("SELECT * FROM DEPARTAMENTOS")
    def consultarUNIDADES_INTERNET(self):
        return self.consultar("SELECT P.ID_UNIDAD, P.NOMBRE_UNIDAD, P.CORD,P.SERVICIO_UNIDAD, P.PROVEEDOR_UNIDAD, P.OBSERVACIONES, P.FECHA_UNIDAD, P.TEL_UNIDAD, T.TIPO FROM UNIDADES_INTERNET AS P INNER JOIN TRANSMISION T ON T.ID_TRANSMISION=P.ID_TRANSMISION")
    def consultarPROVEEDOR(self):
        return self.consultar("SELECT P.ID_PROVEEDOR, P.NOMBRE, P.DESCRIPCION, P.FECHA,P.TELEFONO, T.TIPO  FROM PROVEEDOR AS P INNER JOIN TRANSMISION T ON T.ID_TRANSMISION=P.ID_TRANSMISION")
    def consultarREPORTES(self):
        return self.consultar("SELECT R.ID_REPORTE, R.FOLIO, R.DESCRIPCION, R.FECHA, R.ACUDIO, R.REMOTO_SITIO,R.MOTIVO, R.TELEFONO, R.ATENDIO,  P.NOMBRE FROM REPORTES AS R INNER JOIN PROVEEDOR AS P ON P.ID_PROVEEDOR=R.ID_PROVEEDOR")
    def consultarRED(self):
        return self.consultar("SELECT R.ID_RED, R.SSID, R.PASSWORD, R.SUBIDA, R.BAJADA, P.NOMBRE FROM RED AS R INNER JOIN PROVEEDOR AS P ON R.ID_PROVEEDOR=P.ID_PROVEEDOR")
    def consultarHISTORIAL_NUM_CONEXIONES(self):
        return self.consultar("SELECT H.ID_HISTORIAL_NUM_CONEXIONES,R.SSID,H.FECHA,H.NUMERO FROM HISTORIAL_NUM_CONEXIONES AS H INNER JOIN RED AS R ON R.ID_RED=H.ID_RED")
    def consultarHISTORIAL_CONEXIONES(self):
        return self.consultar("SELECT H.ID_HISTORIAL_CONEXIONES,H.FECHA,R.SSID, H.NOMBRE_HOST, H.IP_HOST, H.MAC_HOST, H.VENDOR FROM HISTORIAL_CONEXIONES AS H INNER JOIN RED AS R ON R.ID_RED=H.ID_RED")
    def consultarCONTROL_RED_ESPECIFICA(self):
        return self.consultar("SELECT C.ID_CONTROL_RED_ESPECIFICA, C.FECHA, R.SSID,C.NO_INV, C.STATUS, C.USUARIO_DIS, C.IP_HOST,C.VENDOR, C.MAC_HOST, C.USUARIO, C.OBSERVACIONES, C.VERIFICADO,C.TIPO,D.NOMBRE FROM CONTROL_RED_ESPECIFICA AS C INNER JOIN RED AS R ON R.ID_RED=C.ID_RED INNER JOIN DEPARTAMENTOS AS D ON D.ID_DEPARTAMENTO=C.ID_DEPARTAMENTO")
    def consultarPRUEBAS_VELOCIDAD(self):
        return self.consultar("SELECT P.ID_PRUEBAS_VELOCIDAD,P.FECHA,P.HORA,P.HOST,P.SPONSOR,R.SSID,P.SUBIDA, P.BAJADA,P.PINGS,P.PINGB,P.PING, P.RESULTADO FROM PRUEBAS_VELOCIDAD AS P INNER JOIN RED AS R ON R.ID_RED=P.ID_RED ")
    def consultarDISPOSITIVOS(self):
        return self.consultar("SELECT D.ID_DISPOSITIVO, D.NOINV, D.NOMBRE, D.DESCRIPCION, D.UBICACION, D.TIPO_CONEXION, R.SSID,DE.NOMBRE FROM DISPOSITIVOS AS D INNER JOIN RED AS R ON R.ID_RED=D.ID_RED INNER JOIN DEPARTAMENTOS AS DE ON DE.ID_DEPARTAMENTO=D.ID_DEPARTAMENTO" )
    def consultarPROBLEMAS_RED(self):
        return self.consultar("SELECT D.ID_PROBLEMA, D.DESCRIPCION, D.FECHA, D.SOLUCION, D.CORREGIDO, D.FECHA_CORRECCION, R.SSID,DE.NOMBRE FROM PROBLEMAS_RED AS D INNER JOIN RED AS R ON R.ID_RED=D.ID_RED INNER JOIN DEPARTAMENTOS AS DE ON DE.ID_DEPARTAMENTO=D.ID_DEPARTAMENTO")